### PR TITLE
Add Automated Deployment Process

### PR DESCRIPTION
**Pull request by peteclodi**
## Proposed changes

Because this repo did not have an Automated Deployment Process that updated version numbers; in `bower.json`, `package.json` and creating a tag, the files still had old and invalid version numbers. This caused a problem with a Hotfix deployment since the versions were out of date and invalid based on SEMVER standards. The solution is to introduce the same `develop` -> `staging` autmated-> `master` system that the other `packback-*` bower packages employ.

Cleaned up the Grunt tasks to only use `grunt-bumper` to update the version numbers and create a release tag

## Types of changes

_What types of changes does your code introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Unit Tests (only unit tests were added)
- [ ] Sprint Deployment

## How has this been tested?

Will be officially tested upon first deployment

## Checklist

_*Pull Requester:* Put an `x` in the boxes that apply. If not applicable, leave the checkbox blank. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask the reviewer._

_*Reviewer:* If you see a blank checkbox where you  believe the action is applicable to the PR you are reviewing (and therefore should have an `x`), engage in a conversation (verbal or over Github comments) with the requester to understand their logic._

- [x] I have added the current sprint milestone to this PR.
- [x] I have attached this PR to all relevant cards.
- [ ] Any dependent changes have been merged and released if needed.
- [ ] My code follows the code style of this project.
- [x] I have added necessary documentation (if appropriate).
- [ ] I have added tests (unit and/or acceptance) that prove my fix is effective or that my feature works.
- [ ] My changes have manual deployment steps, and I have documented these in the current sprint's deployment card.
- [ ] I have checked off and verified that all items within the “Definition of Done” section on this work item have been met.

## Potential opportunities or challenges uncovered as a result of this change

- [ ] I have created inbox cards for any opportunities or future challenges that I was able to recognize in the process making this change.

## Further comments 

_Any other notes you wish to add. If this is a relatively large or complex change, it is recommended to explain why you chose the solution you did and what alternatives you considered, etc (though this can also be conveyed in-person)._

### CODE REVIEW

**Comment by peteclodi** [comment]
[(0) Automate the deployment of pb.styling to match the other pb bower packages [Engineering Requests] [0]](https://trello.com/c/mLZp22vu/2360-0-automate-the-deployment-of-pbstyling-to-match-the-other-pb-bower-packages-engineering-requests-0)

**Comment by vkoves** [comment]
This looks simple enough, but I noticed that minification and concatenation has been removed from the gruntfile. However, since that wasn't done in our past deploy, I assume that's handled by each frontend app using `packback-styling`. Is that correct?

Second, I am overall very confident this should work as expected (as it only uses a basic bumper config), but can/should we test it using a clone/fork of this repo? My main concern would be to make sure that it works properly before we have to use it to deploy.

**Comment by peteclodi** [comment]
@vkoves Quality questions on your part :smile: 

1. You are correct. We no longer "bundle" the styling package. That was a holdover from the days when we only rented books and the site was server rendered.

2. We can certainly test this using your methodology, although the deployment process does have a dependency on Codeship, so I don't know how easy it will be to perform.
My feeling on testing this process is to either trigger a deployment now and see what breaks, if anything, and fix it; or wait until actual deployment, see what breaks and fix it then. In either case we'd have a broken prod version of pb.styling, but since this is the lowest package on the list it can be easily fixed manually to make it stable again, without affecting any of our apps.
We can discuss this decision tomorrow in person as it will make the back and forth much easier.

**Comment by peteclodi** [comment]
Sounds good. We can run some test deployments next week

Pete Clodi
Senior Engineer & Engineering Team Lead
(312) 857-6742
pete@packback.co

**Pull request merged**
